# Generated by Django 6.0.3 on 2026-03-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='is_blocked',
            field=models.BooleanField(default=True),
        ),
    ]
