# Generated by Django 6.0.3 on 2026-03-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_custom_user_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
